"""initial schema

Revision ID: f419b339e175
Revises: 
Create Date: 2026-04-20 18:27:09.314259
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f419b339e175'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playbooks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('extends_playbook_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_base', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['extends_playbook_id'], ['playbooks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', 'version', name='uq_playbooks_slug_version')
    )
    op.create_index('idx_playbooks_slug_active', 'playbooks', ['slug'], unique=False, postgresql_where='is_active = TRUE')
    op.create_table('tools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('handler', sa.String(length=255), nullable=False),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('playbook_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('playbook_id', sa.UUID(), nullable=False),
    sa.Column('config_type', sa.String(length=32), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['playbook_id'], ['playbooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('playbook_id', 'config_type', name='uq_configs_playbook_type')
    )
    op.create_index('idx_configs_playbook', 'playbook_configs', ['playbook_id'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_uid', sa.String(length=128), nullable=False),
    sa.Column('playbook_id', sa.UUID(), nullable=True),
    sa.Column('playbook_slug', sa.String(length=128), nullable=False),
    sa.Column('playbook_version', sa.String(length=32), nullable=False),
    sa.Column('input_file_uri', sa.Text(), nullable=False),
    sa.Column('input_file_hash', sa.String(length=64), nullable=False),
    sa.Column('input_file_name', sa.String(length=512), nullable=True),
    sa.Column('input_file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('input_file_mime', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=True),
    sa.Column('aggregate_confidence', sa.Float(), nullable=True),
    sa.Column('confidence_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('superseded_by_run_id', sa.UUID(), nullable=True),
    sa.Column('requested_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['playbook_id'], ['playbooks.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_uid')
    )
    op.create_index('idx_runs_created', 'runs', ['created_at'], unique=False)
    op.create_index('idx_runs_hash', 'runs', ['input_file_hash'], unique=False)
    op.create_index('idx_runs_playbook_status', 'runs', ['playbook_id', 'status'], unique=False)
    op.create_index('idx_runs_status_pending', 'runs', ['status'], unique=False, postgresql_where="status IN ('created','running','awaiting_hitl')")
    op.create_table('run_corrections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('element_name', sa.String(length=128), nullable=False),
    sa.Column('hint_text', sa.Text(), nullable=False),
    sa.Column('previous_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('succeeded', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_corrections_run', 'run_corrections', ['run_id', 'attempt_number'], unique=False)
    op.create_table('run_elements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('element_name', sa.String(length=128), nullable=False),
    sa.Column('element_type', sa.String(length=32), nullable=True),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('llm_confidence', sa.Float(), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('source_region', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('validation_status', sa.String(length=32), nullable=True),
    sa.Column('validation_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_elements_final', 'run_elements', ['run_id'], unique=False, postgresql_where='is_final = TRUE')
    op.create_index('idx_elements_run', 'run_elements', ['run_id', 'element_name'], unique=False)
    op.create_table('run_hitl_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('checkpoint_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resolution', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resolved_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_hitl_awaiting', 'run_hitl_events', ['status'], unique=False, postgresql_where="status = 'awaiting'")
    op.create_table('run_passes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('pass_name', sa.String(length=32), nullable=False),
    sa.Column('pass_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_blob_uri', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_passes_run', 'run_passes', ['run_id', 'pass_order'], unique=False)
    op.create_table('run_rule_evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('rule_name', sa.String(length=128), nullable=False),
    sa.Column('rule_type', sa.String(length=32), nullable=False),
    sa.Column('fired', sa.Boolean(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('evaluation_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('order_executed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rules_run', 'run_rule_evaluations', ['run_id', 'order_executed'], unique=False)
    op.create_table('trace_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trace_errors', 'trace_events', ['level', 'ts'], unique=False, postgresql_where="level IN ('warning','error')")
    op.create_index('idx_trace_run_ts', 'trace_events', ['run_id', 'ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_trace_run_ts', table_name='trace_events')
    op.drop_index('idx_trace_errors', table_name='trace_events', postgresql_where="level IN ('warning','error')")
    op.drop_table('trace_events')
    op.drop_index('idx_rules_run', table_name='run_rule_evaluations')
    op.drop_table('run_rule_evaluations')
    op.drop_index('idx_passes_run', table_name='run_passes')
    op.drop_table('run_passes')
    op.drop_index('idx_hitl_awaiting', table_name='run_hitl_events', postgresql_where="status = 'awaiting'")
    op.drop_table('run_hitl_events')
    op.drop_index('idx_elements_run', table_name='run_elements')
    op.drop_index('idx_elements_final', table_name='run_elements', postgresql_where='is_final = TRUE')
    op.drop_table('run_elements')
    op.drop_index('idx_corrections_run', table_name='run_corrections')
    op.drop_table('run_corrections')
    op.drop_index('idx_runs_status_pending', table_name='runs', postgresql_where="status IN ('created','running','awaiting_hitl')")
    op.drop_index('idx_runs_playbook_status', table_name='runs')
    op.drop_index('idx_runs_hash', table_name='runs')
    op.drop_index('idx_runs_created', table_name='runs')
    op.drop_table('runs')
    op.drop_index('idx_configs_playbook', table_name='playbook_configs')
    op.drop_table('playbook_configs')
    op.drop_table('tools')
    op.drop_index('idx_playbooks_slug_active', table_name='playbooks', postgresql_where='is_active = TRUE')
    op.drop_table('playbooks')
    # ### end Alembic commands ###
